name: Check code quality
on: [push]
jobs:
  shellcheck:
    runs-on: ubuntu-latest
    steps:
     - name: Run ShellCheck
      uses: ludeeus/action-shellcheck@master
      with:
        severity: error
